### ISSUE TITLE
replacement text appearing twice

### ISSUE THREAD

**Issue by pattyrocks** [federico-terzi/espanso#673]
Hey!

For some reason, randomly, espanso starts to duplicate my replacement. Any ideia what is causing it?
![image](https://user-images.githubusercontent.com/54105891/118982400-c8f63400-b951-11eb-8091-858808bb6a4e.png)

Using Windows 10 64bits

**Comment by federico-terzi** [comment]
Hey @pattyrocks,

I'm sorry you experienced this problem! Perhaps you got multiple worker processes running? 
A way to find out is to open the Task Manager, into the "details" section you should only see 2 instances of "espanso.exe" (one is the daemon and the other is the worker). If you see more, terminate all processes and start espanso again

Let me know if that helps!

Cheers :)

**Comment by pattyrocks** [comment]
It worked! Thank you very much :)

**Comment by federico-terzi** [comment]
@pattyrocks Great! This is a known bug that should be hopefully solved with the next release, thank you for the help!

**Comment by rypptc** [comment]
I have the same issue but in mac m1, I shut down all processes and started again, but it is still happening. Any idea how to solve it?

<img width="411" alt="image" src="https://github.com/espanso/espanso/assets/64696674/4ef9ebc2-d490-432c-951b-7eef8ec93ad4">
