### ISSUE TITLE
inject_delay seems to be ignored in macOS

### ISSUE THREAD

**Issue by tangowithfoxtrot** [federico-terzi/espanso#849]
### Description
`inject_delay` functionality doesn't work in macOS.

### Steps To Reproduce
1. Set `inject_delay: 500` in `default.yml`.
2. Run `espanso restart` or have it reload automatically.
3. Attempt to trigger a text match.

### Expected Result
Much slower text expansion.

### Actual Result
Default expansion speed.

### Environment
macOS 12.0.1
16in MacBook Pro 2019 (Intel)
espanso v0.7.3

### Additional Context
The same `default.yml` configuration works to trigger slower expansion on Pop!_OS 21.04.

**Comment by federico-terzi** [comment]
Hey @tangowithfoxtrot,

Thanks for reporting this issue! I suspect the new v2 should solve this problem, but I'll mark it as a bug report anyway so that we can investigate further

Cheers :)

**Comment by federico-terzi** [comment]
Hey,

I'm closing this issue as the problem should have been fixed in version 2. Feel free to reopen if it doesn't!

Cheers :)

**Comment by tangowithfoxtrot** [comment]
Unfortunately, the issue persists, even on version 2.1.0-alpha. I ran the following to try and make the changes:

`espanso edit default`
Added `inject_delay: 500`
`espanso restart`

Any triggered matches are still replaced at the default speed. Is there something else I should try?

**Comment by federico-terzi** [comment]
@tangowithfoxtrot You're absolutely right, I was able to reproduce... Sorry for the confusion!
I'll reopen it :)

**Comment by federico-terzi** [comment]
Hey @tangowithfoxtrot,

The next version 2.1.3-alpha will include a fix for this problem, thank you for the help!
Keep in mind that text injection on macOS is executed in a "chunked" mode, meaning Espanso injects 20 chars at a time. The `inject_delay` property only refers to the delay between chunks, so you'll need to have a replacement longer than 20 chars to see the difference. 

Cheers :)

**Comment by robinkb** [comment]
Hi @federico-terzi,

Is there a technical reason why injection works in the chunked mode? Can that be controlled? I'm looking into Espanso because I need keystroke automation for a few specific applications where copy-pasting does not work. The Clipboard backend doesn't work, and the Inject backend seems to send keypresses to quickly. Can this be made controllable as well? Maybe a `inject_chunk_size` option?
